library(RODBC)
library(ggplot2)
library(plyr)
library(gtable)
library(grid)
library(reshape2)

bigQueryLink <-"https://bigquery.cloud.google.com/dataset/fh-bigquery:reddit_comments"
begin <- "2017-01-01"
end <- "2017-03-01"

seattleWA_dbhandle <- odbcDriverConnect('driver={SQL Server};server=localhost\\SQLEXPRESS;database=SeattleWA_subreddit;trusted_connection=true')
other_dbhandle <- odbcDriverConnect('driver={SQL Server};server=localhost\\SQLEXPRESS;database=seattle_subreddit;trusted_connection=true')

query <- paste('select comment.*, post.domain, post.author as \'post_author\' 
, post.link_flair_text 
from comment
inner join post on replace(comment.link_id,\'t3_\',\'\') = post.id
                where comment.created_pacific <
\'',end ,'\'
and comment.created_pacific >=\'', begin,'\'', sep="")

commData <- sqlQuery(seattleWA_dbhandle, query)
other_commData <- sqlQuery(other_dbhandle, query)


cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

```{r comments}
numComm <-NROW(commData)
cat("# of comments: ", numComm) 
gold <- sum(commData[,"gilded"])
cat("# gold set to comments:", gold)

commData$YearMonth <- format(as.Date(commData$created_pacific,"America/Los_Angeles"), "%Y-%m")
commCountPerMonth <- count(commData,c( "YearMonth"))

other_commData$YearMonth <- format(as.Date(other_commData$created_pacific,"America/Los_Angeles"), "%Y-%m")
other_commCountPerMonth <- count(other_commData,c( "YearMonth"))

plot_seattleWaCommCountPerMonth <- ggplot(data=commCountPerMonth, 
                     aes(x=YearMonth,y=freq, fill=cbPalette[1:1], width=.75)) +
  geom_bar(width=1,stat="identity") +
  guides(fill=FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

plot_seattleCommCountPerMonth <- ggplot(data=other_commCountPerMonth, 
                     aes(x=YearMonth,y=freq, fill=cbPalette[2:2])) +
  geom_line(aes(group=1), size=2) +
  guides(fill=FALSE) +
  theme(panel.background = element_rect(fill = NA), 
        panel.grid = element_blank()) + 
  expand_limits(y=c(0))





f <- data.frame(YearMonth=commCountPerMonth$YearMonth, seattle=other_commCountPerMonth$freq, seattleWA=commCountPerMonth$freq)

#https://rpubs.com/MarkusLoew/226759

plot_seattleWaCommCountPerMonth <- ggplot(data=f, 
                     aes(x=YearMonth,y=seattleWA, fill=cbPalette[1:1], width=.75)) +
  geom_bar(width=1,stat="identity") +
  guides(fill=FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_line(aes(y=seattle*1.5, group=1), size=1.1) + 
  scale_y_continuous(sec.axis = sec_axis(~./1.5))


#dual comment count
dual <- data.frame(YearMonth = c(commCountPerMonth$YearMonth, seattle_commCountPerMonth$YearMonth), count = c(commCountPerMonth$freq, seattle_commCountPerMonth$freq), sub=c(rep("seattleWA", nrow(commCountPerMonth)), rep("seattle", nrow(seattle_commCountPerMonth))))

ggplot(dual, aes(YearMonth, count)) + geom_bar(aes(fill = sub), 
   width = 0.4, position = position_dodge(width=0.5), stat="identity") +  
   theme(legend.position="top", legend.title = 
   element_blank(),axis.title.x=element_blank(), 
   axis.title.y=element_blank())


#uniques
uniqueAuthorsYearMonth <- ddply(commData, ~YearMonth, summarise, c = length(unique(author)))
other_uniqueAuthorsYearMonth <- ddply(other_commData, ~YearMonth, summarise, c = length(unique(author)))

#total gold by month
goldByYearMonth <- ddply(commData, ~YearMonth,   summarize, s = sum(gilded))
other_goldByYearMonth <- ddply(other_commData, ~YearMonth,   summarize, s = sum(gilded))

#RainerRancor score, count
RR <- ddply(commData[commData$author=="RainierRancor",], ~YearMonth,   summarize, s = sum(score), c=length(author))
other_RR <-ddply(other_commData[other_commData$author=="RainierRancor",], ~YearMonth,   summarize, s = sum(score), c=length(author))

#nimby
nimby <- ddply(commData[grep("NIMBies|NIMBY", commData$body,ignore.case = TRUE),], ~YearMonth,   summarize, s = sum(score), c=length(YearMonth), authors=length(unique(author)))
other_nimby <- ddply(other_commData[grep("NIMBies|NIMBY", other_commData$body,ignore.case = TRUE),], ~YearMonth,   summarize, s = sum(score), c=length(YearMonth), authors=length(unique(author)))

#taco time
tacoTime <- ddply(commData[grep("\\btaco *time[s]?(nw)?\\b", commData$body,ignore.case = TRUE),], ~YearMonth,   summarize, s = sum(score), c = length(YearMonth), authors=length(unique(author)))

other_tacoTime <- ddply(other_commData[grep("\\btaco *time[s]?(nw)?\\b", other_commData$body,ignore.case = TRUE),], ~YearMonth,   summarize, s = sum(score), c = length(YearMonth), authors=length(unique(author)))


#removed
removed <- ddply(commData[grep("^\\[removed\\]", commData$body,ignore.case = TRUE),], ~YearMonth,   summarize, s = sum(score), c = length(YearMonth))

other_removed <- ddply(other_commData[grep("^\\[removed\\]", other_commData$body,ignore.case = TRUE),], ~YearMonth,   summarize, s = sum(score), c = length(YearMonth))

#unique domains
domains <- ddply(commData, ~YearMonth, summarise, c = length(unique(domain)))
other_domains <- ddply(other_commData, ~YearMonth, summarise, c = length(unique(domain)))

#Authors with most comments by year month?
ddply(temp, ~YearMonth+author, summarise, c = length(author))